DROP TABLE IF EXISTS "plane" CASCADE;
DROP TABLE IF EXISTS "passenger" CASCADE;
DROP TABLE IF EXISTS "pilot" CASCADE;
DROP TABLE IF EXISTS "airport" CASCADE;
DROP TABLE IF EXISTS "flight" CASCADE;
DROP TABLE IF EXISTS "trip" CASCADE;
DROP TABLE IF EXISTS "bag" CASCADE;


CREATE TABLE IF NOT EXISTS "plane" (
  pid SERIAL PRIMARY KEY,
  model VARCHAR(100) NOT NULL,
  noBusinessSeats INTEGER NOT NULL,
  noEconomySeats INTEGER NOT NULL,
  carryOnCapacity INTEGER NOT NULL,
  checkInCapacity INTEGER NOT NULL,
  maxWeight INTEGER NOT NULL,
  range INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "passenger" (
  cid SERIAL PRIMARY KEY,
  cname VARCHAR(100) NOT NULL,
  username VARCHAR(15) NOT NULL,
  password VARCHAR(25) NOT NULL
);

CREATE TABLE IF NOT EXISTS "pilot" (
  pilotID SERIAL PRIMARY KEY,
  pname VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS "airport" (
  aid SERIAL PRIMARY KEY,
  aname VARCHAR(50) NOT NULL,
  city VARCHAR(25) NOT NULL,
  numGates INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "flight" (
  fid SERIAL PRIMARY KEY,
  pid INTEGER NOT NULL REFERENCES "plane",
  pilotID INTEGER NOT NULL REFERENCES "pilot",
  startAid INTEGER NOT NULL REFERENCES "airport",
  destinationAid INTEGER NOT NULL REFERENCES "airport",
  distance INTEGER NOT NULL,
  departureGate INTEGER NOT NULL,
  arrivalGate INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "trip" (
  tid SERIAL PRIMARY KEY,
  fid INTEGER NOT NULL REFERENCES "flight",
  cid INTEGER NOT NULL REFERENCES "passenger",
  ticketPrice INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "bag" (
  bid SERIAL PRIMARY KEY,
  bagType VARCHAR(50) NOT NULL,
  weight VARCHAR(25) NOT NULL,
  tid INTEGER NOT NULL REFERENCES "trip"
);
